<?php
/**
 * The integration documentation page.
 *
 * @package POW
 * @license AGPL-3.0-or-later
 */

declare( strict_types = 1 );

namespace POW\Docs;

use POW\Support\Transport;

use POW\Admin\Page as AdminPage;
use POW\Audit\Log;
use POW\Cxml\Parser;
use POW\Http\RateLimiter;
use POW\Http\SetupEndpoint;
use POW\Partners\Partner;
use POW\Partners\Registry;
use POW\Settings;
use POW\Support\Ip;
use POW\Support\Templates;

defined( 'ABSPATH' ) || exit;

/**
 * The buyer-facing integration documentation page: what we speak, where
 * to send it, what comes back, and a self-test that answers what the live
 * endpoint would answer.
 *
 * Shortcode only ([punchout_docs]). Core's Shortcode block already makes
 * it insertable in the block editor, and a real block would mean a JS
 * edit implementation, a build step and a bundle for a page that is
 * static HTML plus one form.
 *
 * Registered BEFORE the master switch gate in Plugin::boot(): a buyer
 * reads this page precisely while punchout is still switched off, and it
 * exposes no session surface. The self-test is the one gated part — with
 * punchout off it says so instead of running.
 *
 * Two rules this class owns rather than the templates, because templates
 * are theme-overridable and a copied template must not be able to lose
 * them:
 *
 * - Samples::annotations() reports ShipTo as a machine token
 *   ('present'/'absent'). The words are chosen here, through __(); the
 *   token itself is never printed.
 * - The connection block is assembled only for a privileged viewer. The
 *   template gates on $privileged as well; a public visitor never learns
 *   which buyers are connected, whichever half is edited.
 */
final class Page {

	public const SHORTCODE = 'punchout_docs';

	/** Nonce action and field name of the self-test form. */
	public const NONCE = 'pow_docs_self_test';
	public const FIELD = 'pow_docs_xml';

	/** Public self-test default for nonpositive settings; the legacy constant name is retained for compatibility. */
	public const SELF_TEST_MIN_PER_MIN = 10;

	public function __construct(
		private Settings $settings,
		private Registry $registry,
		private RateLimiter $rate_limiter,
		private Log $audit,
	) {}

	public function register(): void {
		add_shortcode( self::SHORTCODE, [ $this, 'shortcode' ] );
	}

	/**
	 * @param array<string, mixed>|string $atts Shortcode attributes (none taken).
	 */
	public function shortcode( $atts = [] ): string {
		$privileged = current_user_can( AdminPage::CAP );

		// phpcs:ignore WordPress.Security.NonceVerification.Missing -- reads only the presence of the field, to decide cacheability.
		self::suppress_page_cache( $privileged, (string) ( $_SERVER['REQUEST_METHOD'] ?? '' ), $_POST );

		return $this->render( $privileged );
	}

	/**
	 * Keep this render out of every page cache, and say whether it did.
	 *
	 * Two renders of this page are not the public page: the privileged one
	 * carries the partner roster, and a self-test POST carries a report
	 * about a stranger's paste. A page cache that stored either would
	 * serve it to the next anonymous visitor, which is the one thing the
	 * $privileged gate exists to prevent. An anonymous GET is the same for
	 * everyone and stays cacheable.
	 *
	 * DONOTCACHEPAGE is the constant WP Super Cache, W3 Total Cache,
	 * LiteSpeed Cache and Batcache all honour; nocache_headers() covers
	 * the proxy in front of them.
	 *
	 * @param array<string, mixed> $post Posted fields.
	 * @return bool Whether caching was suppressed.
	 */
	public static function suppress_page_cache( bool $privileged, string $method, array $post ): bool {
		if ( ! $privileged && ! self::is_self_test_post( $method, $post ) ) {
			return false;
		}

		nocache_headers();
		defined( 'DONOTCACHEPAGE' ) || define( 'DONOTCACHEPAGE', true );

		return true;
	}

	/**
	 * The public self-test preserves every positive configured threshold and uses its secure default only for zero/negative settings. It must never express the generic limiter's unlimited mode.
	 */
	public static function self_test_limit( int $configured ): int {
		return RateLimiter::public_limit( $configured, self::SELF_TEST_MIN_PER_MIN );
	}

	/**
	 * The whole page as a string.
	 *
	 * @param bool $privileged Whether the viewer may see connection detail
	 *                         and precise self-test authentication reasons.
	 */
	public function render( bool $privileged ): string {
		if ( ! Transport::request_allowed() ) { return Transport::notice(); }
		try {
			$vars = $this->page_vars( $privileged );
		} catch ( \Throwable $e ) {
			// Every sample is generated by the live codec, so a codec that
			// cannot build one is a real fault: say so on the page and
			// leave a row behind, rather than fataling a public page or
			// printing documentation we cannot stand behind.
			$this->audit->write(
				'docs_render_fail',
				[
					'result' => 'error',
					'detail' => [ 'error' => self::failure_detail( $e ) ],
				]
			);

			return '<p class="pow-docs-error">' . esc_html__( 'The integration documentation could not be generated on this store. Please tell us — the samples on this page are built by the same code that serves live traffic, so this is a fault worth knowing about.', 'punchout-woocommerce' ) . '</p>';
		}

		return Templates::render( 'docs/page', $vars );
	}

	/**
	 * The ShipTo annotation is a token, not a word. Anything else is a
	 * value read off the parsed document and is passed through as data.
	 */
	public static function annotation_value( string $field, string $value ): string {
		if ( 'ShipTo' !== $field ) {
			return $value;
		}

		return 'present' === $value
			? __( 'present', 'punchout-woocommerce' )
			: __( 'absent', 'punchout-woocommerce' );
	}

	/**
	 * What a failed render may say in the audit row.
	 *
	 * The try around page_vars() also covers the self-test, so the message
	 * can quote the visitor's paste — and the paste may carry a live
	 * shared secret. Redacted before it is written anywhere, exactly as
	 * the paste itself is.
	 */
	public static function failure_detail( \Throwable $e ): string {
		return SelfTest::redact( $e->getMessage() );
	}

	/**
	 * The self-test, with every collaborator the public page owes it.
	 *
	 * A Registry means the partner stage runs, and the partner stage is
	 * only safe throttled and logged (SelfTest rules 2 and 3): a null
	 * limiter beside a real registry would sell unmetered credential
	 * guesses from a public page. All three are required here so that
	 * cannot be expressed at the call site.
	 */
	public static function self_test( Registry $registry, RateLimiter $limiter, Log $log ): SelfTest {
		return new SelfTest( new Parser(), $registry, $limiter, $log );
	}

	/**
	 * The message for a POST whose nonce did not verify — an expired form,
	 * usually a page left open or served from a cache. Silence would leave
	 * the visitor staring at an unchanged page wondering what happened.
	 *
	 * '' when this is not that case, so the caller can use it directly.
	 *
	 * @param array<string, mixed> $post Posted fields.
	 */
	public static function expired_nonce_notice( string $method, array $post ): string {
		if ( ! self::is_self_test_post( $method, $post ) || self::is_self_test_request( $method, $post ) ) {
			return '';
		}

		return __( 'This form has expired. Reload the page and try again.', 'punchout-woocommerce' );
	}

	/**
	 * Whether the visitor submitted the self-test form at all, nonce aside.
	 *
	 * The field must be a string. `pow_docs_xml[]=x` makes it an array,
	 * and PHP casting an array to string is a warning printed on a public
	 * page — so the type is part of the gate, not of the handler.
	 *
	 * @param array<string, mixed> $post Posted fields.
	 */
	public static function is_self_test_post( string $method, array $post ): bool {
		return 'POST' === strtoupper( $method ) && isset( $post[ self::FIELD ] ) && is_string( $post[ self::FIELD ] );
	}

	/**
	 * Whether this request is a self-test submission: a POST, carrying the
	 * field, with a nonce we issued. A GET renders the empty box.
	 *
	 * Pure so the rule is provable without WordPress; the caller passes
	 * $_SERVER['REQUEST_METHOD'] and $_POST.
	 *
	 * @param array<string, mixed> $post Posted fields.
	 */
	public static function is_self_test_request( string $method, array $post ): bool {
		if ( ! self::is_self_test_post( $method, $post ) || ! isset( $post['_wpnonce'] ) || ! is_string( $post['_wpnonce'] ) ) {
			return false;
		}

		return false !== wp_verify_nonce( sanitize_text_field( (string) wp_unslash( $post['_wpnonce'] ) ), self::NONCE );
	}

	/**
	 * @return array<string, mixed>
	 */
	private function page_vars( bool $privileged ): array {
		$home_url = untrailingslashit( Transport::supplier_url( home_url() ) );
		$partners = $this->registry->all();

		[ $to_domain, $to_identity ] = self::to_credential( $partners, $privileged );

		$annotations = [];

		foreach ( Samples::annotations() as $field => $value ) {
			$annotations[ $field ] = self::annotation_value( $field, $value );
		}

		return [
			/**
			 * Legacy presentation hint retained for custom documentation templates. Actual emission is configured independently on each connection; the bundled reference documents all flags unconditionally.
			 *
			 * @param bool $enabled Legacy display hint, not an emission control.
			 */
			'reference'      => new Reference( $home_url, $to_domain, $to_identity, (bool) apply_filters( 'pow_delivery_codes_enabled', false ) ),
			'annotations'    => $annotations,
			'setup_request'  => Samples::setup_request(),
			'setup_response' => Samples::setup_response( $home_url . '/punchout/start/EXAMPLE-TOKEN' ),
			'poom'           => Samples::poom(),
			'poom_total'     => Samples::poom_total(),
			'delivery_samples' => Samples::delivery_examples(),
			'cxml_version'   => Samples::VERSION,
			'rate_limit'     => $this->settings->int( 'rate_limit_per_min' ),
			'connections'    => $privileged ? self::connection_rows( $partners, $home_url . '/punchout/setup' ) : [],
			'self_test'      => $this->self_test_box( $privileged ),
			'privileged'     => $privileged,
		];
	}

	/**
	 * How buyers address us. Every connection carries its own To
	 * credential; the page shows the first configured one as the worked
	 * example and tells the reader to use the pair we issued them, so a
	 * store whose customers address it differently is not contradicted.
	 *
	 * @param list<Partner> $partners Registry rows.
	 * @return array{0: string, 1: string}
	 */
	private static function to_credential( array $partners, bool $privileged ): array {
		if ( ! $privileged ) {
			return [ '', '' ];
		}
		foreach ( $partners as $partner ) {
			if ( $partner->is_active() && '' !== $partner->to_identity ) {
				return [ $partner->to_domain, $partner->to_identity ];
			}
		}

		return [ '', '' ];
	}

	/**
	 * The privileged per-connection block: what each active customer is
	 * configured to send and receive. Never assembled for a public view.
	 *
	 * @param list<Partner> $partners Registry rows.
	 * @return list<array{name: string, sender: string, cxml_version: string, deployment_mode: string, return_encoding: string, setup_template: string}>
	 */
	private static function connection_rows( array $partners, string $setup_url ): array {
		$rows = [];

		foreach ( $partners as $partner ) {
			if ( ! $partner->is_active() ) {
				continue;
			}

			$rows[] = [
				'name'            => $partner->name,
				'sender'          => $partner->sender_domain . ' / ' . $partner->sender_identity,
				'cxml_version'    => $partner->cxml_version,
				'deployment_mode' => $partner->deployment_mode,
				'return_encoding' => 'urlencoded' === $partner->return_encoding ? 'cxml-urlencoded' : 'cxml-base64',
				'setup_template'  => Samples::setup_template( $partner, $setup_url ),
			];
		}

		return $rows;
	}

	/**
	 * The self-test box: the empty form on a GET, the form plus a report
	 * (or the reason there is none) on a nonced POST.
	 */
	private function self_test_box( bool $privileged ): string {
		$report = null;
		$xml    = '';
		$method = (string) ( $_SERVER['REQUEST_METHOD'] ?? '' );

		// An expired form says so. The paste itself is NOT echoed back in
		// that case: reflecting unverified POST content onto the page is
		// the thing the nonce is there to stop.
		// phpcs:ignore WordPress.Security.NonceVerification.Missing -- reads the nonce to decide.
		$notice = self::expired_nonce_notice( $method, $_POST );

		// phpcs:ignore WordPress.Security.NonceVerification.Missing -- is_self_test_request() verifies the nonce.
		if ( self::is_self_test_request( $method, $_POST ) ) {
			// Not sanitised and not truncated: it is a document, not a
			// field, and the 2 MB cap is the endpoint's to apply — SelfTest
			// refuses an oversized document with the endpoint's own answer,
			// which is more use to a buyer than a silently truncated parse
			// error. Only ever echoed back through SelfTest::redact(), and
			// never stored.
			// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.NonceVerification.Missing
			$xml = (string) wp_unslash( $_POST[ self::FIELD ] );

			[ $report, $notice ] = $this->run_self_test( $xml, $privileged );
		}

		return Templates::render(
			'docs/self-test',
			[
				'report'     => $report,
				// Bounded on the way out: an oversized paste has already
				// been answered, and there is no reason to echo more of it
				// back than the endpoint would ever have accepted.
				'xml'        => '' !== $xml ? substr( SelfTest::redact( $xml ), 0, SetupEndpoint::MAX_BODY_BYTES ) : '',
				'notice'     => $notice,
				'privileged' => $privileged,
			]
		);
	}

	/**
	 * Run one self-test, or say why it did not run.
	 *
	 * The throttle is the setup endpoint's own limiter on a bucket of its
	 * own: an anonymous XML parser on a public page is a resource, and it
	 * is bounded before the document is looked at. SelfTest charges the
	 * endpoint's unknown-sender bucket as well, so the page cannot be used
	 * to buy credential guesses the endpoint would have refused.
	 *
	 * @return array{0: ?array<string, mixed>, 1: string} Report (or null) and notice.
	 */
	private function run_self_test( string $xml, bool $privileged ): array {
		if ( 'yes' !== (string) $this->settings->get( 'enabled', 'no' ) ) {
			return [ null, __( 'Punchout is switched off on this store, so the self-test cannot run. Everything documented above still describes what we will accept once it is on.', 'punchout-woocommerce' ) ];
		}

		$ip = Ip::client();

		if ( ! $this->rate_limiter->allow( 'docs|' . $ip ) ) {
			return [ null, __( 'Too many self-tests from this address in the last minute. Wait a moment and try again.', 'punchout-woocommerce' ) ];
		}

		$report = self::self_test( $this->registry, $this->rate_limiter, $this->audit )
			->run( $xml, $privileged, $ip );

		// The verdict, the address and who ran it — never the document: it
		// is a paste from a stranger and it may carry a live secret.
		$this->audit->write(
			'docs_self_test',
			[
				'result'  => (string) $report['verdict'],
				'ip'      => $ip,
				'user_id' => get_current_user_id(),
			]
		);

		return [ $report, '' ];
	}
}
