<?php
/**
 * Native visit fixtures: one bound account, many concurrent visits.
 *
 * Every opt-in script under tests/Integration/ that has to put a real
 * WordPress request "inside a visit" needs the same four things, and each of
 * them is easy to get subtly wrong: a session row carrying its own
 * `wc_session_key`, a real `WP_Session_Tokens` entry, a `logged_in` cookie
 * carrying that visit's token (because `wp_get_session_token()` reads the
 * cookie and nothing else, so `wp_set_current_user()` alone leaves every
 * resolver answering "no visit"), and the plugin's own session handler bound
 * to the key. Two employees of one connection are the same WordPress user, so
 * the token and the key are the only things that tell their requests apart.
 *
 * Loaded by an eval-file script, never by tests/bootstrap.php: it calls into
 * WordPress and WooCommerce.
 *
 * @package POW
 * @license AGPL-3.0-or-later
 */

declare( strict_types = 1 );

if ( ! defined( 'ABSPATH' ) ) { throw new RuntimeException( 'Native visit fixtures require WordPress.' ); }

if ( ! function_exists( 'pow_native_visit_store' ) ) {
	function pow_native_visit_store(): POW\Sessions\Store {
		$sessions = POW\Plugin::instance()->sessions();
		if ( ! $sessions ) { throw new RuntimeException( 'Native visit fixtures require a booted plugin.' ); }
		return $sessions;
	}
}

if ( ! function_exists( 'pow_native_open_visit' ) ) {
	/**
	 * One live visit of a connection's bound account.
	 *
	 * The row is what a completed setup plus a redeemed StartPage token
	 * leaves behind: ACTIVE, with this visit's own WP session token, its own
	 * per-visit cart key and the buyer identity the request named. The key is
	 * written through create() here rather than bind_login() because a
	 * fixture has no token to redeem; production mints it in bind_login(),
	 * which is the only place a UNIQUE collision can be retried cheaply.
	 *
	 * @param array<string,mixed> $overrides Extra or replacement columns.
	 */
	function pow_native_open_visit( int $partner_id, int $user_id, array $overrides = [] ): POW\Sessions\Session {
		if ( $partner_id <= 0 || $user_id <= 0 ) { throw new RuntimeException( 'A native visit needs a connection and its bound account.' ); }
		$store    = pow_native_visit_store();
		$identity = (string) ( $overrides['buyer_identity'] ?? '' );
		$token    = (string) ( $overrides['wp_session_token'] ?? WP_Session_Tokens::get_instance( $user_id )->create( time() + 3600 ) );
		$data     = array_replace(
			[
				'partner_id'          => $partner_id,
				'user_id'             => $user_id,
				'status'              => POW\Sessions\Session::ACTIVE,
				'payload_id'          => 'native-visit-' . bin2hex( random_bytes( 10 ) ),
				'body_hash'           => hash( 'sha256', random_bytes( 16 ) ),
				'one_time_token_hash' => hash( 'sha256', random_bytes( 32 ) ),
				'wp_session_token'    => $token,
				'wc_session_key'      => POW\Cart\SessionKey::mint(),
				'buyer_identity'      => '' !== $identity ? $identity : null,
				'buyer_name'          => $overrides['buyer_name'] ?? null,
				'buyer_identity_hash' => '' !== $identity ? hash( 'sha256', $partner_id . '|' . strtolower( $identity ) ) : null,
				'expires'             => gmdate( 'Y-m-d H:i:s', time() + 3600 ),
			],
			$overrides
		);
		$id = $store->create( $data );
		if ( $id <= 0 ) { throw new RuntimeException( 'Native visit row could not be created.' ); }
		$visit = $store->find( $id );
		if ( ! $visit || ! POW\Cart\SessionKey::is_visit_key( (string) $visit->wc_session_key ) ) { throw new RuntimeException( 'Native visit row carries no per-visit cart key.' ); }
		return $visit;
	}
}

if ( ! function_exists( 'pow_native_enter_visit' ) ) {
	/**
	 * Make this request the one that visit is inside.
	 *
	 * `Sessions\Current`, `NativeSessionGuard` and `RouteGuard` all resolve a
	 * visit from (current user, current WP session token), and the token comes
	 * from the `logged_in` cookie, so a CLI request has to carry one. The
	 * cookie is generated by WordPress itself, so its shape cannot drift from
	 * what `wp_parse_auth_cookie()` expects.
	 */
	function pow_native_enter_visit( POW\Sessions\Session $visit ): void {
		$user = get_userdata( $visit->user_id );
		if ( ! $user || '' === $visit->wp_session_token ) { throw new RuntimeException( 'A native visit needs a real account and a bound login token.' ); }
		if ( ! WP_Session_Tokens::get_instance( $visit->user_id )->verify( $visit->wp_session_token ) ) {
			throw new RuntimeException( 'The native visit login token is not live.' );
		}
		wp_set_current_user( $visit->user_id );
		$_COOKIE[ LOGGED_IN_COOKIE ] = wp_generate_auth_cookie( $visit->user_id, time() + 3600, 'logged_in', $visit->wp_session_token );
		wp_cache_delete( $visit->user_id, 'user_meta' );
		pow_native_forget_visit_memo();
		if ( wp_get_session_token() !== $visit->wp_session_token ) { throw new RuntimeException( 'The native visit token did not reach the request.' ); }
	}
}

if ( ! function_exists( 'pow_native_forget_visit_memo' ) ) {
	/**
	 * Drop the plugin's per-request memo of "which visit is this".
	 *
	 * Plugin::current_session() caches a conclusive answer for the whole
	 * request, which is right for a web request and wrong for a CLI script that
	 * plays several requests in one process: without this, entering a second
	 * visit would still be answered with the first. The two private properties
	 * are the seam the unit suites already use.
	 */
	function pow_native_forget_visit_memo(): void {
		$plugin = POW\Plugin::instance();
		foreach ( [ 'current_session' => null, 'session_resolved' => false ] as $property => $value ) {
			$reflection = new ReflectionProperty( $plugin, $property );
			$reflection->setValue( $plugin, $value );
		}
	}
}

if ( ! function_exists( 'pow_native_leave_visit' ) ) {
	/** Back to an ordinary request; the actor is restored so a fixture administrator keeps working. */
	function pow_native_leave_visit( int $actor = 0 ): void {
		unset( $_COOKIE[ LOGGED_IN_COOKIE ] );
		wp_set_current_user( $actor );
		pow_native_forget_visit_memo();
	}
}

if ( ! function_exists( 'pow_native_visit_handler' ) ) {
	/**
	 * The plugin's session handler, hydrated from this visit's own row.
	 *
	 * Core's handler is deliberately never constructed for a visit: its
	 * init_session() destroys a `pow_` row and migrates whatever survives onto
	 * `session_key = '<user id>'`, which is exactly the collision the per-visit
	 * key exists to prevent. The handler is installed as WC()->session so the
	 * cart, the customer data store and the delivery producer all read the
	 * visit's basket.
	 */
	function pow_native_visit_handler( POW\Sessions\Session $visit ): POW\Cart\NativeSessionHandler {
		pow_native_enter_visit( $visit );
		$key     = POW\Cart\SessionKey::for_session( $visit );
		$handler = new POW\Cart\NativeSessionHandler();
		$handler->init();
		if ( ! $handler->in_visit() || ! hash_equals( $key, (string) $handler->get_customer_id() ) ) {
			throw new RuntimeException( 'The native handler did not bind this visit.' );
		}
		return $handler;
	}
}

if ( ! function_exists( 'pow_native_cart_row' ) ) {
	/**
	 * One basket as WooCommerce actually stored it, read byte-exactly.
	 *
	 * @return array<string,mixed>|null
	 */
	function pow_native_cart_row( string $key ): ?array {
		global $wpdb;
		$row = $wpdb->get_row( $wpdb->prepare( 'SELECT * FROM ' . $wpdb->prefix . 'woocommerce_sessions WHERE BINARY session_key = BINARY %s', $key ), ARRAY_A );
		if ( '' !== (string) ( $wpdb->last_error ?? '' ) ) { throw new RuntimeException( 'Native cart row read failed.' ); }
		return is_array( $row ) ? $row : null;
	}
}

if ( ! function_exists( 'pow_native_cart_value' ) ) {
	/**
	 * One key out of a visit's stored basket, decoded the way core stores it.
	 *
	 * @return mixed
	 */
	function pow_native_cart_value( string $key, string $name ) {
		$row = pow_native_cart_row( $key );
		if ( null === $row ) { return null; }
		$data = maybe_unserialize( (string) $row['session_value'] );
		if ( ! is_array( $data ) || ! array_key_exists( $name, $data ) ) { return null; }
		return maybe_unserialize( $data[ $name ] );
	}
}

if ( ! function_exists( 'pow_native_visit_row' ) ) {
	/**
	 * One punchout session row, straight from the table.
	 *
	 * @return array<string,mixed>|null
	 */
	function pow_native_visit_row( int $id ): ?array {
		global $wpdb;
		$row = $wpdb->get_row( $wpdb->prepare( 'SELECT * FROM ' . POW\Installer::sessions_table() . ' WHERE id = %d', $id ), ARRAY_A );
		if ( '' !== (string) ( $wpdb->last_error ?? '' ) ) { throw new RuntimeException( 'Native visit row read failed.' ); }
		return is_array( $row ) ? $row : null;
	}
}

if ( ! function_exists( 'pow_native_bound_account' ) ) {
	/**
	 * An ordinary WooCommerce customer a connection can be bound to.
	 *
	 * Deliberately a plain `customer`: the account buyers punch in as holds no
	 * punchout role and no plugin user meta, and the setup path refuses any
	 * account carrying a privileged capability.
	 */
	function pow_native_bound_account( string $prefix = 'native-account' ): int {
		$suffix = bin2hex( random_bytes( 8 ) );
		$id     = wp_insert_user(
			[
				'user_login' => $prefix . '-' . $suffix,
				'user_email' => $prefix . '-' . $suffix . '@example.invalid',
				'user_pass'  => wp_generate_password( 32 ),
				'role'       => 'customer',
			]
		);
		if ( is_wp_error( $id ) || (int) $id <= 0 ) { throw new RuntimeException( 'Native bound account creation failed.' ); }
		return (int) $id;
	}
}
