<?php
/**
 * The integration documentation page.
 *
 * Everything a buyer's developer needs to connect a procurement system to
 * this store: the endpoints, the identities, the documents in both
 * directions, the status codes, and a self-test.
 *
 * Every sample is generated by the classes that serve live traffic, so
 * the page cannot document a document we do not actually send.
 *
 * Override by copying to {theme}/punchout-woocommerce/docs/page.php, or
 * via the pow_template_docs/page filter.
 *
 * Available variables:
 *
 * @var \POW\Docs\Reference   $reference      The reference model (endpoints, status table, support lists).
 * @var array<string, string> $annotations    Setup-request field => value, already worded.
 * @var string                $setup_request  The annotated inbound sample.
 * @var string                $setup_response The PunchOutSetupResponse sample.
 * @var string                $poom           The PunchOutOrderMessage sample.
 * @var string                $poom_total     Formatted total of the sample basket.
 * @var list<array{version:string,xml:string,total:string,freight_total:string}> $delivery_samples Full enabled examples from the live Builder.
 * @var string                $cxml_version   cXML version of the samples.
 * @var int                   $rate_limit     Configured setup requests per minute (nonpositive = default 30).
 * @var list<array{name: string, sender: string, cxml_version: string, deployment_mode: string, return_encoding: string}> $connections Per-connection block; empty unless privileged.
 * @var string                $self_test      Pre-rendered self-test box.
 * @var bool                  $privileged     Whether the viewer is a store administrator.
 *
 * @package POW
 * @license AGPL-3.0-or-later
 */

defined( 'ABSPATH' ) || exit;
?>
<div class="pow-docs">

	<h2><?php esc_html_e( 'Punchout integration', 'punchout-woocommerce' ); ?></h2>
	<p><?php esc_html_e( 'Punchout lets a buyer browse this store from inside their purchasing system. Their system signs them in over cXML; they fill a cart, review delivery and return priced lines to their requisition. The accepted return may also create a non-payable Punchout Quote on this store. Checkout is a separate exit when the company entitlement permits it.', 'punchout-woocommerce' ); ?></p>
	<p><?php esc_html_e( 'This page is the whole integration: the addresses to send to, the identities involved, the documents in both directions, and every status code we answer with. The samples below are generated by the same code that serves live traffic.', 'punchout-woocommerce' ); ?></p>

	<h3><?php esc_html_e( 'Endpoints', 'punchout-woocommerce' ); ?></h3>
	<table class="pow-docs-table">
		<tbody>
			<?php foreach ( $reference->endpoints() as $pow_label => $pow_url ) : ?>
				<tr>
					<th scope="row"><?php echo esc_html( (string) $pow_label ); ?></th>
					<td><code><?php echo esc_html( (string) $pow_url ); ?></code></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<p><?php esc_html_e( 'Setup requests are POSTed as raw cXML with an XML content type over HTTPS. The HTTP status is always 200: the outcome is in the cXML Status element, which is what procurement systems read.', 'punchout-woocommerce' ); ?></p>

	<h3><?php esc_html_e( 'Identities', 'punchout-woocommerce' ); ?></h3>
	<p><?php esc_html_e( 'Three credentials appear in the header of every setup request. From is the buyer. Sender is the system sending the document, and is the one that authenticates: its domain, identity and shared secret must match what we issued for the connection. To is us, as you address us.', 'punchout-woocommerce' ); ?></p>
	<?php if ( '' !== $reference->to_identity ) : ?>
		<p>
			<?php esc_html_e( 'Address us as:', 'punchout-woocommerce' ); ?>
			<code><?php echo esc_html( $reference->to_domain . ' / ' . $reference->to_identity ); ?></code>
			<?php esc_html_e( 'Where the pair we issued with your connection differs from this, use the pair we issued you.', 'punchout-woocommerce' ); ?>
		</p>
	<?php else : ?>
		<p><?php esc_html_e( 'The To domain and identity are issued with your connection. Use the pair on your setup sheet.', 'punchout-woocommerce' ); ?></p>
	<?php endif; ?>
	<p><?php esc_html_e( 'The shared secret is stored sealed and is never displayed again after it is issued, so keep the copy we send you. It travels only inside the SharedSecret element of your setup request, over HTTPS, and is redacted everywhere we log.', 'punchout-woocommerce' ); ?></p>

	<?php if ( $privileged && [] !== $connections ) : ?>
		<h3><?php esc_html_e( 'Connections configured on this store', 'punchout-woocommerce' ); ?></h3>
		<p><?php esc_html_e( 'Visible to store administrators only.', 'punchout-woocommerce' ); ?></p>
		<table class="pow-docs-table">
			<thead>
				<tr>
					<th scope="col"><?php esc_html_e( 'Customer', 'punchout-woocommerce' ); ?></th>
					<th scope="col"><?php esc_html_e( 'Sender identity', 'punchout-woocommerce' ); ?></th>
					<th scope="col"><?php esc_html_e( 'cXML', 'punchout-woocommerce' ); ?></th>
					<th scope="col"><?php esc_html_e( 'Mode', 'punchout-woocommerce' ); ?></th>
					<th scope="col"><?php esc_html_e( 'Cart return encoding', 'punchout-woocommerce' ); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ( $connections as $pow_connection ) : ?>
					<tr>
						<td><?php echo esc_html( (string) $pow_connection['name'] ); ?></td>
						<td><code><?php echo esc_html( (string) $pow_connection['sender'] ); ?></code></td>
						<td><?php echo esc_html( (string) $pow_connection['cxml_version'] ); ?></td>
						<td><?php echo esc_html( (string) $pow_connection['deployment_mode'] ); ?></td>
						<td><?php echo esc_html( (string) $pow_connection['return_encoding'] ); ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	<?php endif; ?>

	<h3><?php esc_html_e( 'What we speak', 'punchout-woocommerce' ); ?></h3>
	<ul>
		<?php foreach ( $reference->supported() as $pow_item ) : ?>
			<li><?php echo esc_html( (string) $pow_item ); ?></li>
		<?php endforeach; ?>
	</ul>
	<p><?php esc_html_e( 'The DOCTYPE on our documents is a SYSTEM identifier only. We never fetch it, and we do not expect you to: inbound documents declaring entities are refused outright.', 'punchout-woocommerce' ); ?></p>

	<h3><?php esc_html_e( 'The setup request, annotated', 'punchout-woocommerce' ); ?></h3>
	<pre class="pow-docs-sample"><?php echo esc_html( $setup_request ); ?></pre>
	<table class="pow-docs-table">
		<thead>
			<tr>
				<th scope="col"><?php esc_html_e( 'Field', 'punchout-woocommerce' ); ?></th>
				<th scope="col"><?php esc_html_e( 'Value read from the sample', 'punchout-woocommerce' ); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ( $annotations as $pow_field => $pow_value ) : ?>
				<tr>
					<th scope="row"><code><?php echo esc_html( (string) $pow_field ); ?></code></th>
					<td><?php echo esc_html( (string) $pow_value ); ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<p><?php esc_html_e( 'Those values are read back off the sample by the live parser, so this table can never claim a field we do not actually take.', 'punchout-woocommerce' ); ?></p>

	<h3><?php esc_html_e( 'What we answer with', 'punchout-woocommerce' ); ?></h3>
	<p><?php esc_html_e( 'A PunchOutSetupResponse carrying a single-use StartPage URL. Open it in the user\'s browser: it signs them in once, is good for one use within a few minutes, and cannot be replayed.', 'punchout-woocommerce' ); ?></p>
	<pre class="pow-docs-sample"><?php echo esc_html( $setup_response ); ?></pre>

	<h3><?php esc_html_e( 'The cart we send back', 'punchout-woocommerce' ); ?></h3>
	<p><?php esc_html_e( 'This first example has emit_ship_to, emit_delivery_code and emit_delivery_line off, with delivery_notes_policy=off. Physical delivery review remains mandatory; the destination, notes and available estimate stay local while the returned XML contains merchandise only.', 'punchout-woocommerce' ); ?></p>
	<p>
		<?php
		printf(
			/* translators: 1: formatted sample basket total, 2: cXML version of the samples. */
			esc_html__( 'When the user finishes, their cart is posted to your BrowserFormPost URL as a PunchOutOrderMessage. The sample below is a two-line cart totalling %1$s, built by the same builder that serves live traffic, in cXML %2$s.', 'punchout-woocommerce' ),
			esc_html( $poom_total ),
			esc_html( $cxml_version )
		);
		?>
	</p>
	<pre class="pow-docs-sample"><?php echo esc_html( $poom ); ?></pre>
	<p><?php esc_html_e( 'The BuyerCookie is echoed back exactly as you sent it, including an empty one. Cart confirmation currently requires ZAR in WooCommerce and the returned cart. Prices are unit prices; quantities are per line. No currency conversion is performed.', 'punchout-woocommerce' ); ?></p>
	<h4><?php esc_html_e( 'Full enabled examples', 'punchout-woocommerce' ); ?></h4>
	<p><?php esc_html_e( 'These examples enable emit_ship_to, emit_delivery_code and emit_delivery_line, with delivery_notes_policy=item_detail_extrinsic. The invented two-package estimate passes through the same freight-line producer as a confirmed return, then the live Builder. Document totals and the amounts shown here are summed from those lines. The examples do not run a carrier or create a native Quote.', 'punchout-woocommerce' ); ?></p>
	<?php foreach ( $delivery_samples as $pow_sample ) : ?>
		<p><?php printf( /* translators: 1: exact cXML version, 2: freight total in ZAR, 3: basket total in ZAR. */ esc_html__( 'cXML %1$s: one freight line of ZAR %2$s; total including merchandise and freight ZAR %3$s, excluding tax.', 'punchout-woocommerce' ), esc_html( $pow_sample['version'] ), esc_html( $pow_sample['freight_total'] ), esc_html( $pow_sample['total'] ) ); ?></p>
		<pre class="pow-docs-sample"><?php echo esc_html( $pow_sample['xml'] ); ?></pre>
	<?php endforeach; ?>
	<p><?php esc_html_e( 'The automated sample checks validate the exact declared 1.2.008 and 1.2.071 DTDs using verified offline fixtures. Supplier support and valid XML do not establish receiver consumption: confirm destination, code, repeated notes, freight, units and currency in your own receiving system, including any Dynamics 365 tenant.', 'punchout-woocommerce' ); ?></p>

	<h4><?php esc_html_e( 'Return encoding', 'punchout-woocommerce' ); ?></h4>
	<p><?php esc_html_e( 'The cart is posted as a top-level browser form POST to your BrowserFormPost URL. The field is cxml-base64 by default; return_encoding can be set to cxml-urlencoded per connection. Agree and verify the receiving mapping before enabling the connection.', 'punchout-woocommerce' ); ?></p>

	<h3><?php esc_html_e( 'Status codes', 'punchout-woocommerce' ); ?></h3>
	<table class="pow-docs-table">
		<thead>
			<tr>
				<th scope="col"><?php esc_html_e( 'Code', 'punchout-woocommerce' ); ?></th>
				<th scope="col"><?php esc_html_e( 'Text', 'punchout-woocommerce' ); ?></th>
				<th scope="col"><?php esc_html_e( 'What it means', 'punchout-woocommerce' ); ?></th>
				<th scope="col"><?php esc_html_e( 'What to do', 'punchout-woocommerce' ); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ( $reference->status_rows() as $pow_row ) : ?>
				<tr>
					<th scope="row"><?php echo esc_html( (string) $pow_row['code'] ); ?></th>
					<td><?php echo esc_html( (string) $pow_row['text'] ); ?></td>
					<td><?php echo esc_html( (string) $pow_row['meaning'] ); ?></td>
					<td><?php echo esc_html( (string) $pow_row['action'] ); ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>

	<h3><?php esc_html_e( 'Identity extrinsics', 'punchout-woocommerce' ); ?></h3>
	<p><?php esc_html_e( 'Send the user\'s identity as Extrinsic elements on the PunchOutSetupRequest: UserEmail, and UniqueName where your system has one. This recognises the same person within the company and provisions a separate buyer login and cart, without a second employee approval queue. Contact/Email is read as a fallback. Persistent carts are disabled in punchout sessions; a new punchout for the same buyer replaces the previous session.', 'punchout-woocommerce' ); ?></p>
	<p><?php esc_html_e( 'Without any identity we still serve the session, but every punchout looks like a new person. Extrinsic names we do not recognise are ignored, never rejected.', 'punchout-woocommerce' ); ?></p>

	<h3><?php esc_html_e( 'Company addresses and delivery confirmation', 'punchout-woocommerce' ); ?></h3>
	<?php foreach ( $reference->delivery_workflow() as $pow_paragraph ) : ?>
		<p><?php echo esc_html( $pow_paragraph ); ?></p>
	<?php endforeach; ?>
	<h4><?php esc_html_e( 'Independent connection settings', 'punchout-woocommerce' ); ?></h4>
	<p><?php esc_html_e( 'These are the configuration keys and installation defaults, not a disclosure of any company’s settings. Optional export is off by default and does not switch off supplier-side review.', 'punchout-woocommerce' ); ?></p>
	<table class="pow-docs-table">
		<thead><tr><th scope="col"><?php esc_html_e( 'Key', 'punchout-woocommerce' ); ?></th><th scope="col"><?php esc_html_e( 'Default', 'punchout-woocommerce' ); ?></th><th scope="col"><?php esc_html_e( 'Meaning', 'punchout-woocommerce' ); ?></th></tr></thead>
		<tbody><?php foreach ( $reference->delivery_settings() as $pow_key => $pow_setting ) : ?>
			<tr><th scope="row"><code><?php echo esc_html( $pow_key ); ?></code></th><td><code><?php echo esc_html( false === $pow_setting['default'] ? 'false' : ( '' === $pow_setting['default'] ? '""' : $pow_setting['default'] ) ); ?></code></td><td><?php echo esc_html( $pow_setting['note'] ); ?></td></tr>
		<?php endforeach; ?></tbody>
	</table>
	<h4><?php esc_html_e( 'Exact cXML field support', 'punchout-woocommerce' ); ?></h4>
	<table class="pow-docs-table">
		<thead>
			<tr>
				<th scope="col"><?php esc_html_e( 'Field', 'punchout-woocommerce' ); ?></th>
				<th scope="col"><?php esc_html_e( 'Source', 'punchout-woocommerce' ); ?></th>
				<th scope="col"><?php esc_html_e( 'Notes', 'punchout-woocommerce' ); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ( $reference->address_fields() as $pow_field ) : ?>
				<tr>
					<th scope="row"><code><?php echo esc_html( (string) $pow_field['field'] ); ?></code></th>
					<td><?php echo esc_html( (string) $pow_field['source'] ); ?></td>
					<td><?php echo esc_html( (string) $pow_field['note'] ); ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<p><?php esc_html_e( 'Full ShipTo and Address/@addressID are permitted in both 1.2.008 and 1.2.071; addressID requires both address and code export. Direct ItemIn/Extrinsic, Address/@addressIDDomain and SupplierOrderInfo are emitted only for verified 1.2.071. In 1.2.008 these fields are omitted, with no invented replacement. Code-only export therefore has no output in 1.2.008. Unverified versions do not gain optional postal, code or note fields by comparing version numbers.', 'punchout-woocommerce' ); ?></p>
	<h3><?php esc_html_e( 'Company and buyer exit permissions', 'punchout-woocommerce' ); ?></h3>
	<?php foreach ( $reference->exit_policy() as $pow_paragraph ) : ?>
		<p><?php echo esc_html( $pow_paragraph ); ?></p>
	<?php endforeach; ?>

	<h3><?php esc_html_e( 'Rate limits and IP allowlisting', 'punchout-woocommerce' ); ?></h3>
	<p>
		<?php
		printf(
			/* translators: %d: setup requests allowed per minute. */
			esc_html__( 'The setup endpoint accepts %d requests per minute per connection and source address. Over that, it answers cXML Status 550 and nothing else happens; back off and retry. Tell us in advance if a load test needs the limit raised.', 'punchout-woocommerce' ),
			\POW\Http\RateLimiter::public_limit( (int) $rate_limit, 30 )
		);
		?>
	</p>
	<p><?php esc_html_e( 'A connection can also be restricted to a list of source addresses or CIDR ranges. Send us the ranges your procurement system sends from, and tell us before they change: a request from outside the list is refused as an authentication failure, deliberately indistinguishable from a wrong secret.', 'punchout-woocommerce' ); ?></p>

	<h3><?php esc_html_e( 'Rotating the shared secret', 'punchout-woocommerce' ); ?></h3>
	<p><?php esc_html_e( 'Rotation has two slots, so there is no cut-over moment and no outage window. When a new secret is issued the previous one keeps working alongside it: switch your system over whenever you are ready, confirm a successful punchout on the new secret, and tell us — we then close the rotation and the old secret stops being accepted. Ask for a rotation whenever a secret may have been exposed; there is no cost to it.', 'punchout-woocommerce' ); ?></p>

	<h3><?php esc_html_e( 'Not supported', 'punchout-woocommerce' ); ?></h3>
	<ul>
		<?php foreach ( $reference->not_supported() as $pow_item ) : ?>
			<li><?php echo esc_html( (string) $pow_item ); ?></li>
		<?php endforeach; ?>
	</ul>

	<h3><?php esc_html_e( 'Further reading', 'punchout-woocommerce' ); ?></h3>
	<ul>
		<?php foreach ( $reference->links() as $pow_label => $pow_url ) : ?>
			<li><a href="<?php echo esc_url( (string) $pow_url ); ?>" rel="nofollow noopener"><?php echo esc_html( (string) $pow_label ); ?></a></li>
		<?php endforeach; ?>
	</ul>

	<?php echo $self_test; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- template output, escaped within docs/self-test.php. ?>
</div>
