<?php
/** Native admin handlers with recording boundaries; native checks live separately. */
declare(strict_types=1);
require_once dirname(__DIR__).'/Admin/doubles.php';
use PHPUnit\Framework\TestCase;
use POW\Admin\{Actions,Page};
use POW\Partners\{Registry,Registration,Secrets};
use POW\Sessions\Store;
final class AdminActionsTest extends TestCase {
 private array $saved=[]; private AdminDatabase $db; private AdminAudit $audit; private Registry $registry; private Actions $actions;
 protected function setUp(): void {
  foreach(['wpdb','pow_admin_test','pow_test_current_user_id','pow_test_users','pow_test_user_meta','pow_test_options','pow_test_transients','pow_test_valid_nonce','pow_test_mail','pow_test_nocache_headers','pow_test_wc','wp_rewrite','wp_filter','_SERVER','_POST','_GET'] as $k){$this->saved[$k]=[array_key_exists($k,$GLOBALS),$GLOBALS[$k]??null];unset($GLOBALS[$k]);}
  $GLOBALS['pow_admin_test']=['headers'=>[]];$GLOBALS['pow_test_current_user_id']=1;
  $GLOBALS['pow_test_users']=[1=>(object)['ID'=>1,'roles'=>['administrator'],'allcaps'=>['manage_woocommerce'=>true,'read'=>true]],7=>(object)['ID'=>7,'roles'=>['customer'],'allcaps'=>['read'=>true],'user_email'=>'owner@example.invalid']];
  $GLOBALS['pow_test_valid_nonce']='valid';$_SERVER=['REQUEST_METHOD'=>'POST'];$_POST=['partner'=>'20','_wpnonce'=>'valid'];$_GET=[];
  $GLOBALS['wpdb']=$this->db=new AdminDatabase();$this->registry=new Registry(new Secrets(str_repeat('a',32)));$this->audit=new AdminAudit();
  $this->actions=new Actions($this->registry,$this->audit,new Registration($this->registry,new Store(),$this->audit));$this->seed();
 }
 protected function tearDown(): void {foreach($this->saved as $k=>[$exists,$v]){if($exists)$GLOBALS[$k]=$v;else unset($GLOBALS[$k]);}}
 private function seed(array $extra=[]): void {$this->db->rows=[array_replace(['id'=>20,'owner_user_id'=>7,'name'=>'Example Company','status'=>'pending','from_domain'=>'NetworkID','from_identity'=>'BUYER','sender_domain'=>'NetworkID','sender_identity'=>'BUYER','to_domain'=>'NetworkID','to_identity'=>'STORE','mode'=>'requisition_only','deployment_mode'=>'test','return_encoding'=>'base64','cxml_version'=>'1.2.008','secret_current'=>'','secret_previous'=>'','company_profile'=>'{"book":"preserve"}'],$extra)];}
 private function call(string $method): AdminResponse {self::assertTrue(method_exists($this->actions,$method),'Admin action missing: '.$method);try{$this->actions->$method();}catch(AdminResponse $r){return $r;}throw new RuntimeException('Handler did not finish');}
 private function page(array $query=[]): string {$_GET=['tab'=>'partners']+$query;ob_start();try{(new Page(new POW\Settings(),$this->registry,$this->audit))->render();return ob_get_contents();}finally{ob_end_clean();}}
 private function secret(AdminResponse $r): string {preg_match('#<code>([^<]+)</code>#',$r->html,$m);$s=html_entity_decode($m[1]??'',ENT_QUOTES);self::assertTrue(strlen($s)>20,'Expected a credential only in the direct response');return $s;}
 private function no_storage(string $s): void {self::assertFalse(str_contains(json_encode([$this->db->writes,$this->audit->events,$GLOBALS['pow_test_transients']??[],$GLOBALS['pow_test_mail']??[],$GLOBALS['pow_test_options']??[],$GLOBALS['pow_test_user_meta']??[]]),$s),'Plaintext escaped response lifetime');}
 public function test_pending_save_ignores_forged_state_and_secret_and_still_can_approve(): void {
  $_POST+=$this->db->rows[0];$_POST['status']='active';$_POST['secret']='forged';$_POST['generate_secret']='1';$r=$this->call('save_partner');
  self::assertSame('pending',$this->registry->find(20)->status);self::assertSame('',$this->registry->find(20)->secret_current);self::assertSame('',$this->registry->find(20)->secret_previous);
  self::assertTrue(isset($r->args['redirect']));$r=$this->call('approve_partner');$s=$this->secret($r);self::assertTrue($this->registry->find(20)->is_active());$this->no_storage($s);
 }
 public function test_pending_form_has_explicit_approval_without_secret_controls(): void {
  $html=$this->page(['action'=>'edit','partner'=>'20']);self::assertStringContainsString('Pending',$html);self::assertStringContainsString('value="pow_approve_partner"',$html);
  foreach(['name="secret"','name="generate_secret"','value="pow_rotate_partner"','value="pow_reset_partner"'] as $bad)self::assertStringNotContainsString($bad,$html);
 }
 public function test_pending_queue_links_to_preparation(): void {$html=$this->page();self::assertStringContainsString('Pending requests',$html);self::assertStringContainsString('action=edit',$html);self::assertStringContainsString('value="pow_approve_partner"',$html);}
 public function test_missing_to_identity_refuses_approval(): void {foreach(['to_domain','to_identity'] as $field){$this->seed([$field=>'']);$r=$this->call('approve_partner');self::assertSame('pending',$this->registry->find(20)->status);self::assertSame([],$this->db->writes);self::assertStringNotContainsString('<code>',$r->html);self::assertSame([],$this->audit->events);}}
 public function test_all_handlers_reject_get_before_side_effects(): void {foreach(['save_partner','rotate_partner','close_rotation','delete_partner','approve_partner','reset_partner','associate_partner'] as $method){$_SERVER['REQUEST_METHOD']='GET';$_GET=['partner'=>20,'_wpnonce'=>'valid'];$r=$this->call($method);self::assertSame(405,($r->args['response']??null));self::assertSame([],$this->db->writes);self::assertSame([],$this->audit->events);}}
 public function test_all_handlers_reject_nonce_and_capability_without_writes(): void {foreach(['save_partner','rotate_partner','close_rotation','delete_partner','approve_partner','reset_partner','associate_partner'] as $method){foreach(['nonce','capability','array'] as $case){$GLOBALS['pow_test_current_user_id']=$case==='capability'?7:1;$_POST['_wpnonce']=$case==='nonce'?'bad':($case==='array'?[]:'valid');$r=$this->call($method);self::assertSame(403,($r->args['response']??null));self::assertSame([],$this->db->writes);self::assertSame([],$this->audit->events);}}}
 public function test_approval_direct_response_no_store_and_no_get_reveal(): void {$r=$this->call('approve_partner');$s=$this->secret($r);self::assertSame(200,($r->args['response']??null));self::assertTrue(in_array('Cache-Control: no-store, private, max-age=0',$GLOBALS['pow_admin_test']['headers'],true));self::assertTrue(in_array('Referrer-Policy: no-referrer',$GLOBALS['pow_admin_test']['headers'],true));self::assertTrue(($GLOBALS['pow_test_nocache_headers']??0)>0);$this->no_storage($s);self::assertFalse(str_contains($this->page(),$s));$before=$this->db->rows;$this->call('approve_partner');self::assertTrue($before===$this->db->rows,'Stored state unexpectedly changed');}
 public function test_pending_rotate_and_reset_refuse_without_writes(): void {foreach(['rotate_partner','reset_partner'] as $method){$this->call($method);self::assertSame([],$this->db->writes);self::assertSame('',$this->registry->find(20)->secret_current);}}
 public function test_legacy_create_generated_secret_uses_direct_response(): void {$_POST+=$this->db->rows[0];$_POST['partner']='0';$_POST['status']='active';$_POST['generate_secret']='1';$r=$this->call('save_partner');$s=$this->secret($r);$this->no_storage($s);self::assertTrue($this->registry->find(31)->is_active());}
 public function test_rotate_direct_and_close_preserve_overlap_contract(): void {$old=$this->secret($this->call('approve_partner'));$r=$this->call('rotate_partner');$s=$this->secret($r);$p=$this->registry->find(20);self::assertSame(Secrets::SLOT_PREVIOUS,$this->registry->verify_secret($p,$old));$this->no_storage($s);$before=$this->db->rows;$this->call('rotate_partner');self::assertTrue($before===$this->db->rows,'Stored state unexpectedly changed');$this->call('close_rotation');self::assertNull($this->registry->verify_secret($this->registry->find(20),$old));}
 public function test_reset_uses_saved_identity_and_preserves_owner_book(): void {$old=$this->secret($this->call('approve_partner'));$this->call('rotate_partner');$_POST['sender_identity']='forged';$r=$this->call('reset_partner');$s=$this->secret($r);$p=$this->registry->find(20);self::assertNull($this->registry->verify_secret($p,$old));self::assertSame('',$p->secret_previous);self::assertSame('BUYER',$p->sender_identity);self::assertSame(7,$p->owner_user_id);self::assertSame('{"book":"preserve"}',$p->company_profile);$this->no_storage($s);}
 public function test_reset_partial_failure_is_truthful_and_returns_no_secret(): void {$this->call('approve_partner');$this->db->fail_sessions=true;$r=$this->call('reset_partner');self::assertSame('disabled',$this->registry->find(20)->status);self::assertSame('error',$GLOBALS['pow_test_transients']['pow_notice_1']['type']);self::assertStringContainsString('Reset was not completed',$GLOBALS['pow_test_transients']['pow_notice_1']['text']);self::assertStringNotContainsString('<code>',$r->html);}
 public function test_write_failures_never_disclose_or_audit_success(): void {$this->db->fail_write=true;$r=$this->call('approve_partner');self::assertStringNotContainsString('<code>',$r->html);self::assertFalse(in_array('registration_approved',array_column($this->audit->events,0),true));$_POST+=$this->db->rows[0];$_POST['partner']='0';$_POST['generate_secret']='1';$r=$this->call('save_partner');self::assertStringNotContainsString('<code>',$r->html);}
 public function test_admin_can_associate_only_unclaimed_ordinary_owner(): void {$this->seed(['owner_user_id'=>0]);$_POST['owner_user_id']='7';$this->call('associate_partner');self::assertSame(7,$this->registry->find(20)->owner_user_id);self::assertSame('pending',$this->registry->find(20)->status);self::assertStringContainsString('pow_owner_',$this->db->lock_history[0]);self::assertStringContainsString('pow_partner_',$this->db->lock_history[1]);self::assertSame('partner_owner_associated',$this->audit->events[0][0]);self::assertSame(['old_owner_user_id'=>0,'new_owner_user_id'=>7],$this->audit->events[0][1]['detail']);}
 /** No role case: binding refuses on the account's capability, its legacy association meta and the connection's state, never on a role — none exists. */
 public function test_owner_transfer_and_missing_associated_duplicate_accounts_refused(): void {foreach(['transfer','missing','meta','duplicate'] as $case){$this->seed(['owner_user_id'=>$case==='transfer'?8:0]);$_POST['owner_user_id']=$case==='missing'?'99':'7';$GLOBALS['pow_test_users'][7]->roles=['customer'];$GLOBALS['pow_test_user_meta'][7]['_pow_partner_id']=$case==='meta'?5:0;if($case==='duplicate')$this->db->rows[]=array_replace($this->db->rows[0],['id'=>21,'owner_user_id'=>7]);$before=$this->db->rows;$this->call('associate_partner');self::assertTrue($before===$this->db->rows,'Stored state unexpectedly changed');}}
 public function test_owner_claim_rechecks_after_lock(): void {$this->seed(['owner_user_id'=>0]);$_POST['owner_user_id']='7';$this->db->on_lock=function(){$this->db->rows[]=array_replace($this->db->rows[0],['id'=>21,'owner_user_id'=>7]);};$this->call('associate_partner');self::assertSame(0,$this->registry->find(20)->owner_user_id);self::assertSame([],$this->db->writes);}
 public function test_get_notices_never_render_legacy_plaintext(): void {$GLOBALS['pow_test_transients']['pow_notice_1']=['text'=>'Saved','type'=>'success','secret'=>'legacy-sensitive-marker'];self::assertStringNotContainsString('legacy-sensitive-marker',$this->page());}
 public function test_generated_save_after_approval_delivers_even_when_audit_throws(): void {$this->call('approve_partner');$this->audit->fail=true;$_POST+=$this->db->rows[0];$_POST['generate_secret']='1';$s=$this->secret($this->call('save_partner'));self::assertSame(Secrets::SLOT_CURRENT,$this->registry->verify_secret($this->registry->find(20),$s));$this->no_storage($s);}
 public function test_manual_secret_response_is_escaped_and_not_stored_plaintext(): void {$_POST+=$this->db->rows[0];$_POST['partner']='0';$_POST['secret']='<script>synthetic & special credential</script>';$r=$this->call('save_partner');self::assertStringNotContainsString('<script>',$r->html);self::assertStringContainsString('&lt;script&gt;',$r->html);$this->no_storage($_POST['secret']);}
 public function test_association_requires_admin_even_when_helper_called_directly(): void {$this->seed(['owner_user_id'=>0]);$GLOBALS['pow_test_current_user_id']=7;self::assertFalse($this->registry->associate_owner(20,7));self::assertSame([],$this->db->writes);}
 public function test_failed_association_write_does_not_audit_success(): void {$this->seed(['owner_user_id'=>0]);$this->db->fail_write=true;$_POST['owner_user_id']='7';$this->call('associate_partner');self::assertSame(0,$this->registry->find(20)->owner_user_id);self::assertSame([],$this->audit->events);}
 public function test_owner_association_form_is_only_for_unclaimed_legacy_rows(): void {$this->seed(['owner_user_id'=>0]);self::assertStringContainsString('name="owner_user_id"',$this->page(['action'=>'edit','partner'=>20]));$this->seed();$html=$this->page(['action'=>'edit','partner'=>20]);self::assertStringNotContainsString('name="owner_user_id"',$html);self::assertStringContainsString('cannot be transferred',$html);}
 public function test_active_list_actions_are_post_forms_with_no_mutation_links(): void {$this->call('approve_partner');$html=$this->page();self::assertStringContainsString('value="pow_rotate_partner"',$html);self::assertStringNotContainsString('admin-post.php?',$html);self::assertStringContainsString('method="post"',$html);}
 public function test_malformed_input_is_refused_before_any_lookup_or_write(): void {$_POST['name']=[];$r=$this->call('save_partner');self::assertSame(400,$r->args['response']);self::assertSame([],$this->db->writes);}
 public function test_saving_forged_owner_field_cannot_claim_or_transfer(): void {foreach([0,7] as $owner){$this->seed(['owner_user_id'=>$owner]);$_POST+=$this->db->rows[0];$_POST['owner_user_id']='99';$this->call('save_partner');self::assertSame($owner,$this->registry->find(20)->owner_user_id);}}

 public function test_native_response_cannot_replace_explicit_no_store_header(): void {$this->call('approve_partner');$headers=array_values(array_filter($GLOBALS['pow_admin_test']['headers'],fn($h)=>str_starts_with($h,'Cache-Control:')));self::assertSame('Cache-Control: no-store, private, max-age=0',end($headers));}

 public function test_active_save_cannot_forge_a_credentialed_pending_state(): void {$this->call('approve_partner');$before=$this->db->rows;$_POST+=$this->db->rows[0];$_POST['status']='pending';$_POST['generate_secret']='1';$r=$this->call('save_partner');self::assertTrue($before===$this->db->rows,'Stored state unexpectedly changed');self::assertStringNotContainsString('<code>',$r->html);}

 // The My Account endpoint list a visit may open: one column, saved under the connection lock, refused whole when any entry is bad.
 public function test_save_stores_the_endpoint_list_normalised_under_the_lock_and_audits_it(): void {$this->seed(['status'=>'active']);$_POST+=$this->db->rows[0];$_POST['visit_endpoints']=' bulkorder , purchase-lists,bulkorder ';$this->call('save_partner');self::assertSame('success',$GLOBALS['pow_test_transients']['pow_notice_1']['type']);self::assertSame('bulkorder,purchase-lists',$this->registry->find(20)->visit_endpoints);self::assertSame(['bulkorder','purchase-lists'],$this->registry->find(20)->visit_endpoint_list());self::assertStringContainsString('pow_partner_',$this->db->lock_history[0]);self::assertSame(['partner_saved',['visit_endpoints'=>'bulkorder,purchase-lists']],[$this->audit->events[0][0],$this->audit->events[0][1]['detail']]);}
 public function test_save_refuses_a_malformed_endpoint_and_names_it(): void {foreach(['bulkorder,Edit Account','BulkOrder','bulk/order','-lead',['','bulkorder','a,b'],['','Orders']] as $posted){$this->seed(['status'=>'active','visit_endpoints'=>'bulkorder']);$_POST=['partner'=>'20','_wpnonce'=>'valid']+$this->db->rows[0];$_POST['visit_endpoints']=$posted;$label=json_encode($posted);$this->call('save_partner');$notice=$GLOBALS['pow_test_transients']['pow_notice_1'];self::assertSame('error',$notice['type'],$label);self::assertStringContainsString('Not saved, and no other change on the form was kept either',$notice['text']);foreach(array_diff(is_array($posted)?$posted:array_map('trim',explode(',',$posted)),['bulkorder','']) as $bad)self::assertStringContainsString($bad,$notice['text'],$label);self::assertSame([],$this->db->writes,$label);self::assertSame('bulkorder',$this->registry->find(20)->visit_endpoints);self::assertSame([],$this->audit->events);}}
 /** The form's checkboxes post one entry each behind an empty hidden entry; what is ticked is stored in the order posted, the shared login's own pages included. */
 public function test_save_with_checkboxes_stores_the_ticked_pages(): void {$this->seed(['status'=>'active','visit_endpoints'=>'bulkorder']);$_POST+=$this->db->rows[0];$_POST['visit_endpoints']=['','dashboard','bulkorder','orders','customer-logout','late-page','bulkorder'];$this->call('save_partner');self::assertSame('success',$GLOBALS['pow_test_transients']['pow_notice_1']['type']);self::assertSame('dashboard,bulkorder,orders,customer-logout,late-page',$this->registry->find(20)->visit_endpoints);self::assertSame(['partner_saved',['visit_endpoints'=>'dashboard,bulkorder,orders,customer-logout,late-page']],[$this->audit->events[0][0],$this->audit->events[0][1]['detail']]);
  $_POST['visit_endpoints']=[''];$this->call('save_partner');self::assertSame('',$this->registry->find(20)->visit_endpoints,'Nothing ticked clears the list');}
 public function test_save_refuses_payment_pages_on_a_punchout_only_connection(): void {foreach([['','dashboard','payment-methods'],['','add-payment-method','set-default-payment-method'],'delete-payment-method'] as $posted){$this->seed(['status'=>'active','visit_endpoints'=>'bulkorder']);$_POST=['partner'=>'20','_wpnonce'=>'valid']+$this->db->rows[0];$_POST['visit_endpoints']=$posted;$this->call('save_partner');$notice=$GLOBALS['pow_test_transients']['pow_notice_1'];self::assertSame('error',$notice['type']);self::assertStringContainsString('never pays on site',$notice['text']);foreach(array_intersect((array)$posted,POW\Account\VisitEndpoints::PAYMENT) as $page)self::assertStringContainsString($page,$notice['text']);self::assertSame([],$this->db->writes);self::assertSame('bulkorder',$this->registry->find(20)->visit_endpoints);}
  $_POST=['partner'=>'0','_wpnonce'=>'valid']+$this->db->rows[0];$_POST['visit_endpoints']=['','payment-methods'];$this->call('save_partner');self::assertStringContainsString('never pays on site',$GLOBALS['pow_test_transients']['pow_notice_1']['text'],'A new connection is punchout-only too');self::assertSame([],$this->db->writes);}
 /** Only the My Account list may arrive as a list, and only as a flat list of strings; every other field stays scalar. */
 public function test_only_the_endpoint_list_may_be_posted_as_a_list_of_strings(): void {foreach([['x'=>'dashboard'],[['dashboard']],['dashboard',5]] as $bad){$this->seed(['status'=>'active','visit_endpoints'=>'bulkorder']);$_POST=['partner'=>'20','_wpnonce'=>'valid']+$this->db->rows[0];$_POST['visit_endpoints']=$bad;$r=$this->call('save_partner');self::assertSame(400,$r->args['response']??null,json_encode($bad));self::assertSame([],$this->db->writes);}
  foreach(['rotate_partner','close_rotation','delete_partner','approve_partner','reset_partner','associate_partner'] as $method){$_POST=['partner'=>'20','_wpnonce'=>'valid','name'=>['x']];$r=$this->call($method);self::assertSame(400,$r->args['response']??null,$method);}}
 /** A new connection opens the dashboard and nothing else until an administrator ticks more; the column default stays '' for any other writer. */
 public function test_a_new_connection_starts_with_the_dashboard_only(): void {$_POST+=$this->db->rows[0];$_POST['partner']='0';$_POST['status']='active';unset($_POST['visit_endpoints']);$this->call('save_partner');self::assertSame('dashboard',$this->registry->find(31)->visit_endpoints,'A connection saved without the field starts with the dashboard');
  $_POST['visit_endpoints']=['','dashboard'];$_POST['sender_identity']='SECOND';$this->call('save_partner');self::assertSame('dashboard',$this->registry->find(32)->visit_endpoints);
  $_POST['visit_endpoints']=[''];$_POST['sender_identity']='THIRD';$this->call('save_partner');self::assertSame('',$this->registry->find(33)->visit_endpoints,'Unticking the dashboard on a new connection is kept');
  $html=$this->form_with_endpoints(['action'=>'new']);self::assertSame(['dashboard'],$this->ticked($html),'The new-connection form ticks the dashboard and nothing else');}
 public function test_save_refuses_an_endpoint_list_longer_than_the_column(): void {$this->seed(['status'=>'active']);$_POST+=$this->db->rows[0];$_POST['visit_endpoints']=implode(',',array_map(fn($i)=>'endpoint-'.$i,range(100,130)));$this->call('save_partner');self::assertStringContainsString('must fit in 255',$GLOBALS['pow_test_transients']['pow_notice_1']['text']);self::assertSame([],$this->db->writes);}
 /** A save that fails because schema 8 has not landed says so, instead of blaming the Sender identity. */
 public function test_a_save_failing_for_a_missing_column_names_the_schema_not_the_sender(): void {$this->seed(['status'=>'active']);$_POST+=$this->db->rows[0];$_POST['visit_endpoints']='bulkorder';$this->db->fail_write=true;$this->db->columns=['id','name','status'];$this->call('save_partner');$notice=$GLOBALS['pow_test_transients']['pow_notice_1'];self::assertSame('error',$notice['type']);self::assertStringContainsString('column visit_endpoints is missing',$notice['text']);self::assertStringNotContainsString('Sender identity',$notice['text']);$this->db->columns[]='visit_endpoints';$this->call('save_partner');self::assertStringContainsString('is the Sender identity unique?',$GLOBALS['pow_test_transients']['pow_notice_1']['text'],'With the schema in place the old explanation stands');}
 public function test_a_form_without_the_endpoint_field_keeps_the_saved_list(): void {$this->seed(['status'=>'active','visit_endpoints'=>'bulkorder']);$_POST+=$this->db->rows[0];unset($_POST['visit_endpoints']);$_POST['name']='Renamed Company';$this->call('save_partner');self::assertSame('Renamed Company',$this->registry->find(20)->name);self::assertSame('bulkorder',$this->registry->find(20)->visit_endpoints);self::assertSame([],$this->audit->events[0][1]['detail']);}
 /** WooCommerce's endpoint map as the form reads it: its own pages, the plugin's tab, three pages another plugin added (not in order), and titles for some. */
 private function form_with_endpoints(array $query): string {WC()->query=new class{public function get_query_vars(): array{return ['order-pay'=>'order-pay','order-received'=>'order-received','orders'=>'orders','view-order'=>'view-order','downloads'=>'downloads','edit-account'=>'edit-account','edit-address'=>'my-addresses','payment-methods'=>'payment-methods','lost-password'=>'lost-password','customer-logout'=>'customer-logout','add-payment-method'=>'add-payment-method','delete-payment-method'=>'delete-payment-method','set-default-payment-method'=>'set-default-payment-method','subaccounts'=>'subaccounts','punchout-integration'=>'punchout-integration','bulkorder'=>'bulkorder','purchase-lists'=>'purchase-lists','Bad Name'=>'bad'];}public function get_endpoint_title(string $endpoint,string $action=''): string{if('view-order'===$endpoint)throw new LogicException('view-order has no order on an admin screen');return ['orders'=>'Orders','edit-address'=>'Addresses','payment-methods'=>'Payment methods','bulkorder'=>'<em>Quick</em> order'][$endpoint]??'';}};$GLOBALS['wp_rewrite']=$this->rewrite();return $this->page($query);}
 /** WordPress's rewrite endpoints as a site with WooCommerce, this plugin and another plugin holds them in wp-admin: WooCommerce's by address slug, the other plugin's pages (one of them in no WooCommerce map at all), an API address on every URL, one without a query var, one for posts only and one that could not be stored. */
 private function rewrite(): object {return (object)['endpoints'=>[[8191,'wc/file/transient','wc/file/transient'],[8191,'wc-api','wc-api'],[4096,'orders','orders'],[4096,'view-order','view-order'],[4096,'my-addresses','my-addresses'],[4096,'customer-logout','customer-logout'],[4096,'punchout-integration','punchout-integration'],[4161,'bulkorder','bulkorder'],[4161,'purchase-lists','purchase-lists'],[4161,'new-list','new-list'],[4096,'no-query-var',false],[1,'posts-only','posts-only'],[4096,'Bad/Name','Bad/Name']]];}
 /** @return list<string> The ticked checkbox values, in form order. */
 private function ticked(string $html): array {preg_match_all('#<input type="checkbox" name="visit_endpoints\[\]" value="([^"]+)" checked="checked"#',$html,$m);return $m[1];}
 /** @return list<string> Every checkbox value, in form order. */
 private function rows(string $html): array {preg_match_all('#<input type="checkbox" name="visit_endpoints\[\]" value="([^"]+)"#',$html,$m);return $m[1];}
 private function row(string $html,string $name): string {self::assertSame(1,preg_match('#<li><label><input type="checkbox" name="visit_endpoints\[\]" value="'.preg_quote($name,'#').'".*?</li>#',$html,$m),'No row for '.$name);return $m[0];}
 public function test_edit_form_lists_the_registered_pages_as_checkboxes_grouped_with_notes(): void {$this->seed(['status'=>'active','visit_endpoints'=>'dashboard,bulkorder,late-page,orders']);$html=$this->form_with_endpoints(['action'=>'edit','partner'=>'20']);
  self::assertStringContainsString('My Account pages in a visit',$html);self::assertStringNotContainsString('type="text" class="regular-text" name="visit_endpoints"',$html,'The free-text field is gone');self::assertStringContainsString('<input type="hidden" name="visit_endpoints[]" value="" />',$html,'An all-unticked list still reaches the handler');
  $positions=array_map(fn($h)=>strpos($html,'<strong>'.$h.'</strong>'),['WooCommerce','This plugin','Added by other plugins','Ticked, but not found on this site right now']);self::assertSame(array_filter($positions),$positions,'All four groups render');$sorted=$positions;sort($sorted);self::assertSame($sorted,$positions,'WooCommerce first, then this plugin, then other plugins, then entries not found');
  self::assertSame(['dashboard','orders','downloads','edit-address','payment-methods','add-payment-method','delete-payment-method','set-default-payment-method','edit-account','customer-logout','lost-password','order-pay','order-received','punchout-integration','bulkorder','new-list','purchase-lists','subaccounts','late-page'],$this->rows($html),'Every registered page once, in its group, other plugins alphabetically, a single order folded into Orders; a page only WordPress\'s rewrite endpoints know is offered; an address on every URL, one without a query var, one for posts only and a name that could not be stored are not');
  self::assertSame(['dashboard','orders','bulkorder','late-page'],$this->ticked($html),'The stored list is ticked, including an entry that is not registered right now');
  self::assertStringContainsString('Dashboard <code>/my-account/</code>',$this->row($html,'dashboard'));self::assertStringContainsString('Shows only the pages ticked here.',$this->row($html,'dashboard'));
  self::assertStringContainsString('Orders <code>orders</code>',$this->row($html,'orders'));self::assertStringContainsString('Shows the order list, which every buyer of this connection shares.',$this->row($html,'orders'));self::assertStringContainsString('page stays closed in a visit.',$this->row($html,'orders'));self::assertStringContainsString('Addresses <code>edit-address</code> <span class="description">(address: my-addresses)</span>',$this->row($html,'edit-address'));
  self::assertStringContainsString('Quick order <code>bulkorder</code>',$this->row($html,'bulkorder'),'Another plugin\'s title is used, as text');self::assertStringContainsString('Added by another plugin.',$this->row($html,'bulkorder'));self::assertStringContainsString('Creating users inside a visit is blocked',$html);
  self::assertStringContainsString('<code>new-list</code></label> <span class="description">Added by another plugin.</span>',$this->row($html,'new-list'),'A page known only as a rewrite endpoint is labelled by its name');
  self::assertStringContainsString('Punchout integration <code>punchout-integration</code>',$this->row($html,'punchout-integration'));
  self::assertStringContainsString('Not found on this site right now.',$this->row($html,'late-page'));self::assertStringContainsString('Untick it to remove it.',$this->row($html,'late-page'));self::assertStringNotContainsString('registered with WooCommerce',$html);
  foreach(['downloads'=>'Shared by every buyer','edit-address'=>'from a normal login','edit-account'=>'email address and password'] as $name=>$note){self::assertStringContainsString($note,$this->row($html,$name),$name);self::assertStringNotContainsString('disabled',$this->row($html,$name),$name);}
  foreach(['customer-logout','lost-password','order-pay','order-received','punchout-integration'] as $name){$row=$this->row($html,$name);self::assertStringContainsString(' disabled="disabled"',$row,$name);self::assertStringContainsString('Stays closed in a visit.',$row,$name);self::assertStringNotContainsString('checked',$row,$name);}
  foreach(['pow-endpoint-warning','#d63638','breaks the punchout visit','Exposes this connection','still refuses checkout'] as $gone)self::assertStringNotContainsString($gone,$html,'No red warning for an effect that cannot happen: '.$gone);
  self::assertSame(1,preg_match('#<label>Add a page by name: <input type="text" name="visit_endpoints\[\]" value="" class="regular-text"[^>]*/></label>#',$html),'A name box adds a page the list does not show');self::assertStringContainsString('lowercase letters, digits and hyphens',$html);}
 /** The case that broke on a live store: another plugin adds its pages to WooCommerce's map only on the front end, so wp-admin sees them as rewrite endpoints only. They are offered, ticked or not, so a page unticked once can be ticked again, and a page no source shows can be typed. */
 public function test_a_page_wp_admin_sees_only_as_a_rewrite_endpoint_can_be_unticked_and_ticked_again(): void {$this->seed(['status'=>'active','visit_endpoints'=>'dashboard,bulkorder,purchase-lists,new-list']);WC()->query=new class{public function get_query_vars(): array{return ['orders'=>'orders','view-order'=>'view-order','punchout-integration'=>'punchout-integration'];}public function get_endpoint_title(string $endpoint,string $action=''): string{return '';}};$GLOBALS['wp_rewrite']=(object)['endpoints'=>[[8191,'wc-api','wc-api'],[4096,'orders','orders'],[4096,'view-order','view-order'],[4096,'punchout-integration','punchout-integration'],[4161,'bulkorder','bulkorder'],[4161,'purchase-lists','purchase-lists'],[4161,'new-list','new-list']]];
  $html=$this->page(['action'=>'edit','partner'=>'20']);self::assertSame(['dashboard','orders','punchout-integration','bulkorder','new-list','purchase-lists'],$this->rows($html));self::assertSame(['dashboard','bulkorder','new-list','purchase-lists'],$this->ticked($html));self::assertStringNotContainsString('Ticked, but not found',$html,'Nothing the store registers is called missing');
  $_POST+=$this->db->rows[0];$_POST['visit_endpoints']=['','dashboard','bulkorder','purchase-lists',''];$this->call('save_partner');self::assertSame('dashboard,bulkorder,purchase-lists',$this->registry->find(20)->visit_endpoints,'new-list unticked');
  $html=$this->page(['action'=>'edit','partner'=>'20']);self::assertContains('new-list',$this->rows($html),'The unticked page is still offered');self::assertFalse(in_array('new-list',$this->ticked($html),true),'and shown unticked');
  $_POST['visit_endpoints']=['','dashboard','bulkorder','purchase-lists','new-list',''];$this->call('save_partner');self::assertSame('dashboard,bulkorder,purchase-lists,new-list',$this->registry->find(20)->visit_endpoints,'and ticking it again stores it again');
  unset($GLOBALS['wp_rewrite']);$_POST['visit_endpoints']=['','dashboard','bulkorder','purchase-lists','new-list','typed-page'];$this->call('save_partner');self::assertSame('success',$GLOBALS['pow_test_transients']['pow_notice_1']['type']);self::assertSame('dashboard,bulkorder,purchase-lists,new-list,typed-page',$this->registry->find(20)->visit_endpoints,'A name typed in the box is stored like a ticked box');
  $html=$this->page(['action'=>'edit','partner'=>'20']);self::assertSame(['dashboard','bulkorder','purchase-lists','new-list','typed-page'],$this->ticked($html),'Without any source for them the stored pages keep ticked rows');
  $_POST['visit_endpoints']=['','dashboard','Typed Page'];$this->call('save_partner');$notice=$GLOBALS['pow_test_transients']['pow_notice_1'];self::assertSame('error',$notice['type']);self::assertStringContainsString('Typed Page',$notice['text']);self::assertStringContainsString('type one page name in lowercase letters, digits and hyphens',$notice['text']);self::assertSame('dashboard,bulkorder,purchase-lists,new-list,typed-page',$this->registry->find(20)->visit_endpoints);}
 /** A page a WooCommerce feature adds at run time is WooCommerce's: its account content is defined inside WooCommerce. Anything else stays with the other plugins' pages. */
 public function test_a_page_woocommerce_itself_provides_is_listed_with_woocommerce(): void {if(!defined('WC_ABSPATH'))define('WC_ABSPATH',dirname(__DIR__).'/fixtures/woocommerce-feature/');require_once dirname(__DIR__).'/fixtures/woocommerce-feature/feature-endpoint.php';
  $hook=fn(mixed $function): object=>(object)['callbacks'=>[10=>['x'=>['function'=>$function,'accepted_args'=>1]]]];
  $GLOBALS['wp_filter']=['woocommerce_account_order-withdrawal_endpoint'=>$hook(['POW_Test_Woo_Feature_Endpoint','render']),'woocommerce_account_wishlist_endpoint'=>$hook('pow_test_woo_feature_render'),'woocommerce_account_bulkorder_endpoint'=>$hook(static function(): void {}),'woocommerce_account_offers_endpoint'=>$hook('no_such_function')];
  $this->seed(['status'=>'active','visit_endpoints'=>'dashboard']);WC()->query=new class{public function get_query_vars(): array{return ['orders'=>'orders','view-order'=>'view-order','wishlist'=>'wishlist','order-withdrawal'=>'withdraw-order','bulkorder'=>'bulkorder','offers'=>'offers'];}public function get_endpoint_title(string $endpoint,string $action=''): string{return 'order-withdrawal'===$endpoint?'Withdraw order':'';}};
  $html=$this->page(['action'=>'edit','partner'=>'20']);self::assertSame(['dashboard','orders','order-withdrawal','wishlist','bulkorder','offers'],$this->rows($html),'WooCommerce\'s feature pages follow its standard set; a closure defined elsewhere and a callback that cannot be traced are another plugin\'s');
  self::assertStringContainsString('Withdraw order <code>order-withdrawal</code> <span class="description">(address: withdraw-order)</span></label></li>',$this->row($html,'order-withdrawal'),'No other-plugin note on WooCommerce\'s own page');self::assertStringContainsString('Added by another plugin.',$this->row($html,'bulkorder'));}
 /** Every connection is punchout-only, so the payment-method rows are shown disabled, unticked even when the row names them, with the reason. */
 public function test_payment_rows_are_disabled_on_a_punchout_only_connection(): void {$this->seed(['status'=>'active','visit_endpoints'=>'dashboard,payment-methods']);$html=$this->form_with_endpoints(['action'=>'edit','partner'=>'20']);
  foreach(POW\Account\VisitEndpoints::PAYMENT as $name){$row=$this->row($html,$name);self::assertStringContainsString(' disabled="disabled"',$row,$name);self::assertStringNotContainsString('checked',$row,$name);self::assertStringContainsString('Punchout-only connections never pay on site.',$row,$name);}
  self::assertSame(['dashboard'],$this->ticked($html));self::assertSame(9,substr_count($html,'disabled="disabled"'),'Only the four payment rows and the five pages that never open are disabled');}
 /** Without WooCommerce's endpoint map the form still offers the dashboard and keeps every stored entry. */
 public function test_without_an_endpoint_map_the_form_keeps_the_stored_entries(): void {$this->seed(['status'=>'active','visit_endpoints'=>'bulkorder,orders']);WC()->query=null;$html=$this->page(['action'=>'edit','partner'=>'20']);self::assertSame(['dashboard','bulkorder','orders'],$this->rows($html));self::assertSame(['bulkorder','orders'],$this->ticked($html));self::assertStringNotContainsString('<strong>WooCommerce</strong>',substr($html,strpos($html,'Ticked, but not found on this site right now')));}

}
