<?php
/** Native admin handlers with recording boundaries; native checks live separately. */
declare(strict_types=1);
require_once dirname(__DIR__).'/Admin/doubles.php';
use PHPUnit\Framework\TestCase;
use POW\Admin\{Actions,Page};
use POW\Partners\{Registry,Registration,Secrets};
use POW\Sessions\Store;
final class AdminActionsTest extends TestCase {
 private array $saved=[]; private AdminDatabase $db; private AdminAudit $audit; private Registry $registry; private Actions $actions;
 protected function setUp(): void {
  foreach(['wpdb','pow_admin_test','pow_test_current_user_id','pow_test_users','pow_test_user_meta','pow_test_options','pow_test_transients','pow_test_valid_nonce','pow_test_mail','pow_test_nocache_headers','_SERVER','_POST','_GET'] as $k){$this->saved[$k]=[array_key_exists($k,$GLOBALS),$GLOBALS[$k]??null];unset($GLOBALS[$k]);}
  $GLOBALS['pow_admin_test']=['headers'=>[]];$GLOBALS['pow_test_current_user_id']=1;
  $GLOBALS['pow_test_users']=[1=>(object)['ID'=>1,'roles'=>['administrator'],'allcaps'=>['manage_woocommerce'=>true,'read'=>true]],7=>(object)['ID'=>7,'roles'=>['customer'],'allcaps'=>['read'=>true],'user_email'=>'owner@example.invalid']];
  $GLOBALS['pow_test_valid_nonce']='valid';$_SERVER=['REQUEST_METHOD'=>'POST'];$_POST=['partner'=>'20','_wpnonce'=>'valid'];$_GET=[];
  $GLOBALS['wpdb']=$this->db=new AdminDatabase();$this->registry=new Registry(new Secrets(str_repeat('a',32)));$this->audit=new AdminAudit();
  $this->actions=new Actions($this->registry,$this->audit,new Registration($this->registry,new Store(),$this->audit));$this->seed();
 }
 protected function tearDown(): void {foreach($this->saved as $k=>[$exists,$v]){if($exists)$GLOBALS[$k]=$v;else unset($GLOBALS[$k]);}}
 private function seed(array $extra=[]): void {$this->db->rows=[array_replace(['id'=>20,'owner_user_id'=>7,'name'=>'Example Company','status'=>'pending','from_domain'=>'NetworkID','from_identity'=>'BUYER','sender_domain'=>'NetworkID','sender_identity'=>'BUYER','to_domain'=>'NetworkID','to_identity'=>'STORE','mode'=>'requisition_only','deployment_mode'=>'test','return_encoding'=>'base64','cxml_version'=>'1.2.008','secret_current'=>'','secret_previous'=>'','company_profile'=>'{"book":"preserve"}'],$extra)];}
 private function call(string $method): AdminResponse {self::assertTrue(method_exists($this->actions,$method),'Admin action missing: '.$method);try{$this->actions->$method();}catch(AdminResponse $r){return $r;}throw new RuntimeException('Handler did not finish');}
 private function page(array $query=[]): string {$_GET=['tab'=>'partners']+$query;ob_start();try{(new Page(new POW\Settings(),$this->registry,$this->audit))->render();return ob_get_contents();}finally{ob_end_clean();}}
 private function secret(AdminResponse $r): string {preg_match('#<code>([^<]+)</code>#',$r->html,$m);$s=html_entity_decode($m[1]??'',ENT_QUOTES);self::assertTrue(strlen($s)>20,'Expected a credential only in the direct response');return $s;}
 private function no_storage(string $s): void {self::assertFalse(str_contains(json_encode([$this->db->writes,$this->audit->events,$GLOBALS['pow_test_transients']??[],$GLOBALS['pow_test_mail']??[],$GLOBALS['pow_test_options']??[],$GLOBALS['pow_test_user_meta']??[]]),$s),'Plaintext escaped response lifetime');}
 public function test_pending_save_ignores_forged_state_and_secret_and_still_can_approve(): void {
  $_POST+=$this->db->rows[0];$_POST['status']='active';$_POST['secret']='forged';$_POST['generate_secret']='1';$r=$this->call('save_partner');
  self::assertSame('pending',$this->registry->find(20)->status);self::assertSame('',$this->registry->find(20)->secret_current);self::assertSame('',$this->registry->find(20)->secret_previous);
  self::assertTrue(isset($r->args['redirect']));$r=$this->call('approve_partner');$s=$this->secret($r);self::assertTrue($this->registry->find(20)->is_active());$this->no_storage($s);
 }
 public function test_pending_form_has_explicit_approval_without_secret_controls(): void {
  $html=$this->page(['action'=>'edit','partner'=>'20']);self::assertStringContainsString('Pending',$html);self::assertStringContainsString('value="pow_approve_partner"',$html);
  foreach(['name="secret"','name="generate_secret"','value="pow_rotate_partner"','value="pow_reset_partner"'] as $bad)self::assertStringNotContainsString($bad,$html);
 }
 public function test_pending_queue_links_to_preparation(): void {$html=$this->page();self::assertStringContainsString('Pending requests',$html);self::assertStringContainsString('action=edit',$html);self::assertStringContainsString('value="pow_approve_partner"',$html);}
 public function test_missing_to_or_entitlement_refuses_approval(): void {foreach(['to_domain','to_identity','mode'] as $field){$this->seed([$field=>'']);$r=$this->call('approve_partner');self::assertSame('pending',$this->registry->find(20)->status);self::assertSame([],$this->db->writes);self::assertStringNotContainsString('<code>',$r->html);self::assertSame([],$this->audit->events);}}
 public function test_all_handlers_reject_get_before_side_effects(): void {foreach(['save_partner','rotate_partner','close_rotation','delete_partner','approve_partner','reset_partner','associate_partner'] as $method){$_SERVER['REQUEST_METHOD']='GET';$_GET=['partner'=>20,'_wpnonce'=>'valid'];$r=$this->call($method);self::assertSame(405,($r->args['response']??null));self::assertSame([],$this->db->writes);self::assertSame([],$this->audit->events);}}
 public function test_all_handlers_reject_nonce_and_capability_without_writes(): void {foreach(['save_partner','rotate_partner','close_rotation','delete_partner','approve_partner','reset_partner','associate_partner'] as $method){foreach(['nonce','capability','array'] as $case){$GLOBALS['pow_test_current_user_id']=$case==='capability'?7:1;$_POST['_wpnonce']=$case==='nonce'?'bad':($case==='array'?[]:'valid');$r=$this->call($method);self::assertSame(403,($r->args['response']??null));self::assertSame([],$this->db->writes);self::assertSame([],$this->audit->events);}}}
 public function test_approval_direct_response_no_store_and_no_get_reveal(): void {$r=$this->call('approve_partner');$s=$this->secret($r);self::assertSame(200,($r->args['response']??null));self::assertTrue(in_array('Cache-Control: no-store, private, max-age=0',$GLOBALS['pow_admin_test']['headers'],true));self::assertTrue(in_array('Referrer-Policy: no-referrer',$GLOBALS['pow_admin_test']['headers'],true));self::assertTrue(($GLOBALS['pow_test_nocache_headers']??0)>0);$this->no_storage($s);self::assertFalse(str_contains($this->page(),$s));$before=$this->db->rows;$this->call('approve_partner');self::assertTrue($before===$this->db->rows,'Stored state unexpectedly changed');}
 public function test_pending_rotate_and_reset_refuse_without_writes(): void {foreach(['rotate_partner','reset_partner'] as $method){$this->call($method);self::assertSame([],$this->db->writes);self::assertSame('',$this->registry->find(20)->secret_current);}}
 public function test_legacy_create_generated_secret_uses_direct_response(): void {$_POST+=$this->db->rows[0];$_POST['partner']='0';$_POST['status']='active';$_POST['generate_secret']='1';$r=$this->call('save_partner');$s=$this->secret($r);$this->no_storage($s);self::assertTrue($this->registry->find(31)->is_active());}
 public function test_rotate_direct_and_close_preserve_overlap_contract(): void {$old=$this->secret($this->call('approve_partner'));$r=$this->call('rotate_partner');$s=$this->secret($r);$p=$this->registry->find(20);self::assertSame(Secrets::SLOT_PREVIOUS,$this->registry->verify_secret($p,$old));$this->no_storage($s);$before=$this->db->rows;$this->call('rotate_partner');self::assertTrue($before===$this->db->rows,'Stored state unexpectedly changed');$this->call('close_rotation');self::assertNull($this->registry->verify_secret($this->registry->find(20),$old));}
 public function test_reset_uses_saved_identity_and_preserves_owner_book(): void {$old=$this->secret($this->call('approve_partner'));$this->call('rotate_partner');$_POST['sender_identity']='forged';$r=$this->call('reset_partner');$s=$this->secret($r);$p=$this->registry->find(20);self::assertNull($this->registry->verify_secret($p,$old));self::assertSame('',$p->secret_previous);self::assertSame('BUYER',$p->sender_identity);self::assertSame(7,$p->owner_user_id);self::assertSame('{"book":"preserve"}',$p->company_profile);$this->no_storage($s);}
 public function test_reset_partial_failure_is_truthful_and_returns_no_secret(): void {$this->call('approve_partner');$this->db->fail_sessions=true;$r=$this->call('reset_partner');self::assertSame('disabled',$this->registry->find(20)->status);self::assertSame('error',$GLOBALS['pow_test_transients']['pow_notice_1']['type']);self::assertStringContainsString('Reset was not completed',$GLOBALS['pow_test_transients']['pow_notice_1']['text']);self::assertStringNotContainsString('<code>',$r->html);}
 public function test_write_failures_never_disclose_or_audit_success(): void {$this->db->fail_write=true;$r=$this->call('approve_partner');self::assertStringNotContainsString('<code>',$r->html);self::assertFalse(in_array('registration_approved',array_column($this->audit->events,0),true));$_POST+=$this->db->rows[0];$_POST['partner']='0';$_POST['generate_secret']='1';$r=$this->call('save_partner');self::assertStringNotContainsString('<code>',$r->html);}
 public function test_admin_can_associate_only_unclaimed_ordinary_owner(): void {$this->seed(['owner_user_id'=>0]);$_POST['owner_user_id']='7';$this->call('associate_partner');self::assertSame(7,$this->registry->find(20)->owner_user_id);self::assertSame('pending',$this->registry->find(20)->status);self::assertStringContainsString('pow_owner_',$this->db->lock_history[0]);self::assertStringContainsString('pow_partner_',$this->db->lock_history[1]);self::assertSame('partner_owner_associated',$this->audit->events[0][0]);self::assertSame(['old_owner_user_id'=>0,'new_owner_user_id'=>7],$this->audit->events[0][1]['detail']);}
 public function test_owner_transfer_and_missing_provisioned_duplicate_accounts_refused(): void {foreach(['transfer','missing','role','meta','duplicate'] as $case){$this->seed(['owner_user_id'=>$case==='transfer'?8:0]);$_POST['owner_user_id']=$case==='missing'?'99':'7';$GLOBALS['pow_test_users'][7]->roles=$case==='role'?['punchout_buyer']:['customer'];$GLOBALS['pow_test_user_meta'][7]['_pow_partner_id']=$case==='meta'?5:0;if($case==='duplicate')$this->db->rows[]=array_replace($this->db->rows[0],['id'=>21,'owner_user_id'=>7]);$before=$this->db->rows;$this->call('associate_partner');self::assertTrue($before===$this->db->rows,'Stored state unexpectedly changed');}}
 public function test_owner_claim_rechecks_after_lock(): void {$this->seed(['owner_user_id'=>0]);$_POST['owner_user_id']='7';$this->db->on_lock=function(){$this->db->rows[]=array_replace($this->db->rows[0],['id'=>21,'owner_user_id'=>7]);};$this->call('associate_partner');self::assertSame(0,$this->registry->find(20)->owner_user_id);self::assertSame([],$this->db->writes);}
 public function test_get_notices_never_render_legacy_plaintext(): void {$GLOBALS['pow_test_transients']['pow_notice_1']=['text'=>'Saved','type'=>'success','secret'=>'legacy-sensitive-marker'];self::assertStringNotContainsString('legacy-sensitive-marker',$this->page());}
 public function test_generated_save_after_approval_delivers_even_when_audit_throws(): void {$this->call('approve_partner');$this->audit->fail=true;$_POST+=$this->db->rows[0];$_POST['generate_secret']='1';$s=$this->secret($this->call('save_partner'));self::assertSame(Secrets::SLOT_CURRENT,$this->registry->verify_secret($this->registry->find(20),$s));$this->no_storage($s);}
 public function test_manual_secret_response_is_escaped_and_not_stored_plaintext(): void {$_POST+=$this->db->rows[0];$_POST['partner']='0';$_POST['secret']='<script>synthetic & special credential</script>';$r=$this->call('save_partner');self::assertStringNotContainsString('<script>',$r->html);self::assertStringContainsString('&lt;script&gt;',$r->html);$this->no_storage($_POST['secret']);}
 public function test_association_requires_admin_even_when_helper_called_directly(): void {$this->seed(['owner_user_id'=>0]);$GLOBALS['pow_test_current_user_id']=7;self::assertFalse($this->registry->associate_owner(20,7));self::assertSame([],$this->db->writes);}
 public function test_failed_association_write_does_not_audit_success(): void {$this->seed(['owner_user_id'=>0]);$this->db->fail_write=true;$_POST['owner_user_id']='7';$this->call('associate_partner');self::assertSame(0,$this->registry->find(20)->owner_user_id);self::assertSame([],$this->audit->events);}
 public function test_owner_association_form_is_only_for_unclaimed_legacy_rows(): void {$this->seed(['owner_user_id'=>0]);self::assertStringContainsString('name="owner_user_id"',$this->page(['action'=>'edit','partner'=>20]));$this->seed();$html=$this->page(['action'=>'edit','partner'=>20]);self::assertStringNotContainsString('name="owner_user_id"',$html);self::assertStringContainsString('cannot be transferred',$html);}
 public function test_active_list_actions_are_post_forms_with_no_mutation_links(): void {$this->call('approve_partner');$html=$this->page();self::assertStringContainsString('value="pow_rotate_partner"',$html);self::assertStringNotContainsString('admin-post.php?',$html);self::assertStringContainsString('method="post"',$html);}
 public function test_malformed_input_is_refused_before_any_lookup_or_write(): void {$_POST['name']=[];$r=$this->call('save_partner');self::assertSame(400,$r->args['response']);self::assertSame([],$this->db->writes);}
 public function test_saving_forged_owner_field_cannot_claim_or_transfer(): void {foreach([0,7] as $owner){$this->seed(['owner_user_id'=>$owner]);$_POST+=$this->db->rows[0];$_POST['owner_user_id']='99';$this->call('save_partner');self::assertSame($owner,$this->registry->find(20)->owner_user_id);}}

 public function test_native_response_cannot_replace_explicit_no_store_header(): void {$this->call('approve_partner');$headers=array_values(array_filter($GLOBALS['pow_admin_test']['headers'],fn($h)=>str_starts_with($h,'Cache-Control:')));self::assertSame('Cache-Control: no-store, private, max-age=0',end($headers));}

 public function test_active_save_cannot_forge_a_credentialed_pending_state(): void {$this->call('approve_partner');$before=$this->db->rows;$_POST+=$this->db->rows[0];$_POST['status']='pending';$_POST['generate_secret']='1';$r=$this->call('save_partner');self::assertTrue($before===$this->db->rows,'Stored state unexpectedly changed');self::assertStringNotContainsString('<code>',$r->html);}

}
